import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
data=pd.read_csv('retail_sales_data.csv')
df=pd.DataFrame(data)
print(df.describe())
# print(df.head(10))

# print(df.isnull().any()) no null,value found 
#  top sales per product category
top_salep_cat=df.groupby(['Product_Category'])['Total_Amount'].sum().sort_values(ascending=False).head(5)
print(top_salep_cat)
# visualization by pie chart 
figs,axes=plt.subplots(2,2,figsize=(12,8),facecolor="#94d0f8")
figs.suptitle("Retail Sales Analysis Dashboard ", fontsize='16',fontweight='bold',family='Arial')
from charts.plot_ppie import plot_professional_pie 
plot_professional_pie(
               data=top_salep_cat,
               title='Top Sales by Category',
               top_n=5,
               value_label='PKR',
               label_font='Calibri',
               title_font='Arial',
               show_others=False,
               start_angle=160,
               ax=axes[0,1]
                )

# avergae sales per costumers By gender 
avg_gender=df.groupby(['Customer_Gender'])['Total_Amount'].mean().sort_values(ascending=False)
print(avg_gender)

from charts.plot_bar import plot_bar_chart
plot_bar_chart(
    x_labels=avg_gender.index,
    values=avg_gender.values,
    title='Average Sales Per Customer Gender',
    title_font='Arial',
    xlabel='Gender',
    ylabel='Sales',
    axis_font='Verdana',
    figure_facecolor="#f5f5f5",
    thresholds=('Male', 'Female'),
    colors=("#B42504", "#AB7622", "#ee9c19"),
    rotation=0,
    show_minor_ticks=True,
    show_minor_labels=False,
    ax=axes[0,0]  
    )

# total revenue by store location
rev_store_loc=df.groupby(["Store_Location"])["Total_Amount"].sum().sort_values(ascending=False)
print(rev_store_loc)
plot_bar_chart(
    x_labels=rev_store_loc.index,
    values=rev_store_loc.values,
    title='Total Revenue Generated By stores',
    title_font='Arial',
    xlabel='Store Location',
    ylabel='Revenue Generated',
    axis_font='Verdana',
    figure_facecolor="#f5f5f5",
    thresholds=('5090.66', '7804.17'),
    colors=("#B42504", "#AB7622", "#ee9c19"),
    rotation=0,
    show_minor_ticks=True,
    show_minor_labels=False,
    ax=axes[1,0]  
    )


# revenue per month
df['Month']=pd.to_datetime(df["Date"]).dt.to_period('M')
monthly_sales=df.groupby(['Month'])['Total_Amount'].sum().sort_values(ascending=False)
print(monthly_sales)
#month wiseproduct price trend 
trend_month=df.groupby(['Month'])["Price_Per_Unit"].mean()
print(trend_month)
from charts.plot_line import plot_line_chart
plot_line_chart(trend_month.index.to_timestamp(), trend_month.values, title='Montly Trend Of Per UNit Price', xlabel='Month', ylabel='Unit Price', label='Price Variation', linestyle='solid',
                    linewidth=2, color="#01063B", marker='o', markersize=8,
                    markerfacecolor=None, markeredgecolor='black', legend=True, ax=axes[1,1])

plt.tight_layout(rect=[0, 0, 1, 0.95])  # Reserve space for suptitle (top=0.95)
plt.subplots_adjust(hspace=0.4, wspace=0.3)  # Add space between rows/columns
# plt.show()
fig,axs=plt.subplots(1,2,figsize=(13,9),facecolor="#94d0f8")
fig.suptitle("Retail Sales Analysis Dashboard 2", fontsize='16',fontweight='bold',family='Arial')
# daily trend in product price 
trend_daily=df.groupby(["Date"])['Price_Per_Unit'].mean()
print(trend_daily)
from charts.plot_scatter import plot_scatter_chart
plot_scatter_chart(x=trend_daily.index, y=trend_daily.values, title='Daily Trend in Product Unit Price', title_font='Arial', xlabel='Dates',
                        ylabel='Product Unit Price',label_font='Verdana', label='Daily Variation',
                       color="#2b6a2b", marker='D', markersize=10,
                       edgecolor='black', alpha=0.85, legend=True, annotate=True,
                       ax=axs[0])
axs[0].xaxis.set_major_locator(mdates.AutoDateLocator())
axs[0].xaxis.set_major_formatter(mdates.DateFormatter('%b %d'))
axs[0].tick_params(axis='x', rotation=30, labelsize=7)

# Optional trend line
rolling_avg = trend_daily.rolling(window=7).mean()
axs[0].plot(trend_daily.index, rolling_avg, color='red', linewidth=2, label='7-day Trend')
axs[0].legend()
axs[0].grid(True, linestyle='--', alpha=0.6)

# payment methods usage frequency
pay_method=df.groupby(["Payment_Method"])['Total_Amount'].sum().sort_values(ascending=False)
print(pay_method)
from charts.plot_hbar import plot_hbar_chart_
plot_hbar_chart_(
    y_labels=pay_method.index,
    values=pay_method.values,
    title='Payment Method Summary',
    title_font='Arial',
    xlabel='Frequency',
    ylabel='Payment Method',
    axis_font='Verdana',
    figure_facecolor="#f5f5f5",
    thresholds=('Mobile Wallet','Cash','Card' ),
    colors=("#B42504", "#AB7622", "#ee9c19"),
    show_minor_ticks=True,
    show_minor_labels=False,
    ax=axs[1]
)


plt.tight_layout(rect=[0, 0, 1, 0.95])  
plt.subplots_adjust(hspace=0.4, wspace=0.3)  
plt.show()
